import Head from 'next/head'
import { useEffect, useState } from 'react';
import ItemList from '../components/items/BigItemList';
import Nav from '../components/Nav';


export default function Home() {
  const[items, setItems] = useState([]);
  const [loading, setLoading] = useState(false);
  useEffect(() =>{
    setLoading(true);
    const fetchItems = async () => {
      await fetch('http://localhost:8080/sites/LagerApp/Backend/index.php')
      .then(res => res.json())
      .then(response => setItems(response));
      setLoading(false);
    }
    fetchItems();
  },[])


  return (
    <div>
      <Head>
        <title>Storage App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {loading ? <p>Loading..</p> : <ItemList data={items} />}
    </div>
  )
}
